experiment:
  name: example_momentum_strategy
  version: 1.0.0
  seed: 42
  description: Example momentum strategy with reproducibility

data:
  source: data/stock_prices.parquet
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  frequency: daily
  universe: SP500

features:
  window_sizes: [10, 20, 50, 100]
  indicators:
    - sma
    - ema
    - rsi
    - macd
    - bollinger_bands
  selected:
    - returns_10d
    - returns_20d
    - volume_ratio
    - rsi_14
  target: forward_returns_1d

model:
  type: gradient_boosting
  parameters:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
    random_state: 42
  
validation:
  method: time_series_cv
  n_splits: 5
  test_size: 252
  gap: 5

performance:
  metrics:
    - sharpe_ratio
    - max_drawdown
    - total_return
    - win_rate
  bounds:
    sharpe_ratio: [0.5, 3.0]
    max_drawdown: [-0.3, 0.0]
    win_rate: [0.45, 0.65]